
-- PAYDAY 2 v1.143.246 | 03 Jun 2025, 10:41 AM (UTC)
-- Generated by dumpmenunodes.lua, all modifications to this file will be lost when it is dumped again

-- This determines whether DLC advert entries are hidden (future entries will also be hidden). Set to false to disable this
-- behavior
MainMenuStreamliner.HideDLCAds = true

-- To hide a given menu entry, simply delete the preceding -- of the line corresponding to the entry to be hidden
-- The 'true' value at the end of each entry has no significance, it is merely used to ensure that the entry exists in the table
-- due to the way Lua works. DLC advert entries are not listed here as there are far too many (use MainMenuStreamliner.HideDLCAds
-- above instead as that is much more efficient and will work on all entries added in future without requiring additional changes
-- to be made)

MainMenuStreamliner.EntriesToHide = {
	options = {
		-- CONTROLS
--		controls = true,

		-- VIDEO
--		video = true,

		-- SOUND
--		sound = true,

		-- Network
--		network = true,

		-- User Interface
--		user_interface = true,

		-- Accessibility
--		accessibility = true,

		-- Social Hub
		socialhub = true,

		-- ADVANCED
--		advanced = true,

		-- Custom Achievements
		BeardLibAchievementsMenu = true,

		-- BeardLib Mods Manager
--		BeardLibMenu = true,

		-- <no translation for "blt_divider">
--		blt_divider = true,

		-- BLT Mods
--		blt_mods_new = true,

		-- Mod Options
--		blt_options = true,

		-- <no translation for "divider">
--		divider = true,

		-- DEFAULT OPTIONS
--		option_default = true,

		-- <no translation for "divider">
--		divider = true,

		-- Link Starbreeze Nebula
		no_sbz_account = true,

		-- Go to your Starbreeze Nebula account
		has_sbz_account = true,

		-- <no translation for "divider">
--		divider = true,

		-- CREDITS
		credits = true
	},
	accessibility_options = {
		-- Hurt indicators - colorblind assist mode
--		toggle_color_blind_hit_direction = true,

		-- <no translation for "divider">
--		divider = true,

		-- Motion Dot
--		accessibility_dot = true,

		-- Motion Dot Size
--		accessibility_dot_size = true,

		-- Hide Motion Dot during ADS
--		toggle_dot_hide_ads = true,

		-- Screen Flash Color
--		accessibility_screenflash_color_choice = true,

		-- Damage Flash Color
--		accessibility_screenflash_color_hit_flash_choice = true,

		-- Blur Zone Flash Color
--		accessibility_screenflash_color_blurzone_choice = true,

		-- Disable Tinnitus Ringing Effect
--		accessibility_sounds_tinnitus_toggle = true
	},
	sound = {
		-- MUSIC VOLUME
--		music_volume = true,

		-- SFX VOLUME
--		sfx_volume = true,

		-- VOICE CHAT VOLUME
--		voice_volume = true,

		-- USE VOICE CHAT
--		toggle_voicechat = true,

		-- USE PUSH TO TALK
--		toggle_push_to_talk = true,

		-- Mute Contractor Voices
--		toggle_mute_heist_vo = true,

		-- <no translation for "divider">
--		divider = true,

		-- <no translation for "divider">
--		divider = true,

		-- Custom heist Playlist
--		jukebox_heist_playlist = true,

		-- Custom heist tracks
--		jukebox_heist_tracks = true,

		-- <no translation for "divider">
--		divider = true,

		-- Custom stealth playlist
--		jukebox_ghost_playlist = true,

		-- Custom stealth tracks
--		jukebox_ghost_tracks = true,

		-- <no translation for "divider">
--		divider = true,

		-- Custom menu playlist
--		jukebox_menu_playlist = true,

		-- Custom menu tracks
--		jukebox_menu_tracks = true,

		-- <no translation for "divider">
--		divider = true,

		-- <no translation for "divider">
--		divider = true,

		-- DEFAULT SOUND OPTIONS
--		sound_option_default = true
	},
	controls = {
		-- HORIZONTAL LOOK SENSITIVITY
--		camera_sensitivity_horizontal = true,

		-- VERTICAL LOOK SENSITIVITY
--		camera_sensitivity_vertical = true,

		-- HORIZONTAL AIMING SENSITIVITY
--		camera_zoom_sensitivity_horizontal = true,

		-- VERTICAL AIMING SENSITIVITY
--		camera_zoom_sensitivity_vertical = true,

		-- SEPARATE SENSITIVITY
--		toggle_camera_sensitivity_separate = true,

		-- FOV Relative Sensitivity
--		toggle_fov_based_zoom = true,

		-- INVERT Y-AXIS
--		toggle_invert_camera_vertically = true,

		-- HOLD TO AIM
--		toggle_hold_to_steelsight = true,

		-- HOLD TO RUN
--		toggle_hold_to_run = true,

		-- HOLD TO CROUCH
--		toggle_hold_to_duck = true,

		-- Interaction Style
--		tap_to_interact_choice = true,

		-- Cancel message during hold
--		tap_to_interact_show_text_toggle = true,

		-- Toggle Timer
--		tap_to_interact_time_set = true,

		-- EDIT KEYS
--		customize_controller = true,

		-- <no translation for "divider">
--		divider = true,

		-- DEFAULT CONTROL OPTIONS
--		control_option_default = true
	},
	adv_video = {
		-- Vsync
--		toggle_vsync = true,

		-- Depth of Field
--		toggle_dof = true,

		-- Chromatic Aberration
--		toggle_chromatic = true,

		-- Flush GPU
--		choose_gpu_flush = true,

		-- Use HQ weapons
--		toggle_use_thq_weapon_parts = true,

		-- TEXTURE QUALITY
--		choose_texture_quality = true,

		-- Shadow Quality
--		choose_shadow_quality = true,

		-- ANISOTROPIC FILTERING
--		choose_anisotropic = true,

		-- ANIMATION QUALITY
--		choose_anim_lod = true,

		-- Anti aliasing
--		choose_aa = true,

		-- Ambient Occlusion
--		choose_ao = true,

		-- Parallax mapping
--		toggle_parallax = true,

		-- Corpse Limit
--		choose_corpse_limit = true,

		-- FRAME RATE LIMIT
--		choose_fps_cap = true,

		-- COLOR GRADING
--		choose_color_grading = true,

		-- ALIENWARE LIGHTFX
--		use_lightfx = true,

		-- FOV adjustment
--		fov_multiplier = true,

		-- Use Acceleration Camera Effect
--		use_headbob = true,

		-- Procedural arm animation
--		toggle_arm_animation = true,

		-- Streaming Chunk KB
--		max_streaming_chunk = true
	},
	user_interface_options = {
		-- Loading Screen: Hints
--		toggle_loading_hints = true,

		-- Show VR descriptions
--		toggle_vr_descs = true,

		-- Throwable Outline
--		toggle_throwable_contour = true,

		-- Ammo Outline
--		toggle_ammo_contour = true,

		-- SUBTITLE
--		toggle_subtitle = true,

		-- Hit confirm indicator
--		toggle_hit_indicator = true,

		-- Objective reminder message
--		toggle_objective_reminder = true,

		-- Show Ammo Reserve
--		toggle_alt_hud_ammo = true,

		-- <no translation for "infamy_roman_divider">
--		infamy_roman_divider = true,

		-- Infamy rank roman numerals
--		toggle_infamy_roman_rank = true,

		-- Infamy card roman numerals
--		toggle_infamy_roman_card = true,

		-- <no translation for "divider">
--		divider = true,

		-- DEFAULT USER INTERFACE OPTIONS
--		user_interface_option_default = true
	},
	main = {
		-- Play Online
--		crimenet = true,

		-- Play Offline
--		crimenet_offline = true,

		-- Social Hub
		social_hub = true,

		-- <no translation for "inventory1">
--		inventory1 = true,

		-- Career
--		story_missions = true,

		-- Inventory
--		inventory = true,

		-- Achievements
--		achievements = true,

		-- <no translation for "divider_test2">
--		divider_test2 = true,

		-- Steam Items
--		steam_inventory = true,

		-- FBI Files
		fbi_files = true,

		-- Community
		gamehub = true,

		-- <no translation for "divider_infamy">
--		divider_infamy = true,

		-- OPTIONS
--		options = true,

		-- <no translation for "ad_dummy">
--		ad_dummy = true

		-- Movie Theater
		movie_theater = true,

		-- The End
		movie_the_end = true,
	},
	socialhub_options = {
		-- SHOW CODE
		toggle_socialhub_hide_code = true,

		-- INVITE SETTINGS
		socialhub_invite = true,

		-- NOTIFICATION SETTINGS
--		socialhub_notification = true
	},
	video = {
		-- RESOLUTION
--		resolution = true,

		-- Monitor
--		choose_video_adapter = true,

		-- FULLSCREEN
--		toggle_fullscreen = true,

		-- BRIGHTNESS
--		brightness = true,

		-- Effect quality
--		effect_quality = true,

		-- ADVANCED
--		adv_video = true,

		-- <no translation for "divider">
--		divider = true,

		-- DEFAULT VIDEO OPTIONS
--		video_option_default = true
	},
	network_options = {
		-- Packet Throttling
--		toggle_throttling = true,

		-- Forwarding
--		toggle_net_forwarding = true,

		-- Use Compression
--		toggle_net_use_compression = true,

		-- <no translation for "divider">
--		divider = true,

		-- DEFAULT NETWORK OPTIONS
--		network_option_default = true
	}
}
